### ISSUE TITLE
2D Scatter Contour Building Example

### ISSUE THREAD

**Issue by humphreylee** [mthh/contour-isobands-rs#1]
Thanks for creating both contour-rs and contour-isobands-rs crates. I love the example result/images. I have a use case where I think these crates would be very helpful. Below are my data -> X & Y scatter data. I would like to create density contour as shown in image below, which was generated using Julia (with Makie). Please Ignore the trendlines. I have been using [plotter-rs](https://github.com/plotters-rs/plotters) to create other plots from the data. Would `file_writer.write` a better approach to create the image in pdf, png or svg format? Thanks very much.

```
X	Y
275	5700
315	7350
250	6324
275	5041
280	5800
234	5300
246	4800
271	5529
201	4100
210	4103
222	4500
205	4492
205	4432
215	4254
267	7507
235	6430
235	6530
235	6430
180	4090
180	4240
180	3993
180	2860
212	6280
215	5645
230	5815
285	9850
296	11318
152	4467
255	10751
258	7200
297	7385
228	5303
225	5237
257	7533
261	6896
257	6859
303	9004
220	6327
233	6577
187	4110
200	6077
185	7039
190	6465
238	7278
181	5188
333	11760
292	8471
216	6168
188	4783
250	8635
234	7261
239	5693
225	5463
244	6959
230	6236
172	3100
150	2400
292	8452
281	7655
259	6438
301	7844
329	7844
```

![image](https://github.com/mthh/contour-isobands-rs/assets/66808535/6d8119df-a433-4150-9971-843b98b8abe0)

**Comment by mthh** [comment]
Hi and thanks for your feedback!

There are a few transformations to do to your data so that it matches the inputs expected by contour-isobands; I'm going to set up an example repository to use contour-isobands with data in the same form as yours, then plot the result with plotters (I think this could be useful to other users).
I'll probably get back to you on this in a few days.

**Comment by humphreylee** [comment]
I am still keen to see a working example. Thanks.

**Comment by mthh** [comment]
See the code in the following repository for a generic example about plotting points and isolines with plotters : https://github.com/mthh/plotting-contours.
Since your example plot used lines, the demo code uses the [contour](https://crates.io/crates/contour) crate (https://github.com/mthh/contour-rs) but I will push some changes to also provide an example with the [contour-isobands](https://crates.io/crates/contour-isobands) crate (https://github.com/mthh/contour-isobands-rs).

![plot](https://github.com/mthh/contour-isobands-rs/assets/12172162/f698f993-6030-4514-ab75-43739623c46b)

Note also that to go from scattered points like yours to contour lines, it's necessary to create a regular grid (this is the format expected by contour / contour-isobands) and it's desirable to interpolate from the scattered points to the regular grid (this is what I did in my demo code with a kernel density estimation).

You then need to choose threshold values appropriate to your data to tell contour / contour-isobands where to create lines / bands.

**Comment by humphreylee** [comment]
Thanks very much for sharing a working example.
